### List books
GET http://localhost:3000/livros

### Create book
POST http://localhost:3000/livros
Content-Type: application/json

{ "titulo": "O Cortiço", "autor": "Aluísio Azevedo", "isbn": "9788508040001" }

### Book availability
GET http://localhost:3000/livros/1/disponibilidade

### Create copy
POST http://localhost:3000/exemplares
Content-Type: application/json

{ "livroId": 1, "tombo": "BIB-0002" }